### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by connecteev** [baiyutang/paravu#5]
OneStepAtATime:laravel_iview_paravu kunalpunjabi$ npm run watch

> @ watch /Users/kunalpunjabi/Code/vuejs_examples/VUE_COMPONENT_FRAMEWORKS/laravel_iview_paravu
> npm run development -- --watch

> @ development /Users/kunalpunjabi/Code/vuejs_examples/VUE_COMPONENT_FRAMEWORKS/laravel_iview_paravu
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-07-01T04_50_03_172Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `npm run development -- --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-07-01T04_50_03_479Z-debug.log
OneStepAtATime:laravel_iview_paravu kunalpunjabi$ npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-07-01T04_50_09_561Z-debug.log
OneStepAtATime:laravel_iview_paravu kunalpunjabi$ npm run dev

> @ dev /Users/kunalpunjabi/Code/vuejs_examples/VUE_COMPONENT_FRAMEWORKS/laravel_iview_paravu
> npm run development

> @ development /Users/kunalpunjabi/Code/vuejs_examples/VUE_COMPONENT_FRAMEWORKS/laravel_iview_paravu
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-07-01T04_50_13_652Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-07-01T04_50_13_696Z-debug.log

**Comment by baiyutang** [comment]
ok, I will check it tomorrow. then,I reply you.

**Comment by baiyutang** [comment]
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Maybe you can run `npm install` firstly

**Comment by connecteev** [comment]
Ok weird, it works today! I have it installed. I don't want to file another issue...but http://127.0.0.1:8000 loads nothing (I'm not seeing anything) unless I go to http://127.0.0.1:8000/index.html
Bit strange...
Also is there an admin for adding posts? Thanks!

**Comment by baiyutang** [comment]
> Ok weird, it works today! I have it installed. I don't want to file another issue...but http://127.0.0.1:8000 loads nothing (I'm not seeing anything) unless I go to http://127.0.0.1:8000/index.html
> Bit strange...
> Also is there an admin for adding posts? Thanks!

yes, beckend of the blog is:  ` http://127.0.0.1:8000/#/login `,
 but before this ,you should register an user like this in postman

![image](https://user-images.githubusercontent.com/10782183/60564466-51857e80-9d92-11e9-9b11-ae1bf0ae80a3.png)

**Comment by baiyutang** [comment]
> Ok weird, it works today! I have it installed. I don't want to file another issue...but http://127.0.0.1:8000 loads nothing (I'm not seeing anything) unless I go to http://127.0.0.1:8000/index.html
> Bit strange...
> Also is there an admin for adding posts? Thanks!

remember  `npm run dev` OR  `npm run prod`,if you build the page first time.
